# index.yml
http:
  routers:
    index:
      rule: Path(`/`)
      service: "public-service"
      middlewares:
        - common-redirect-to-https

  services:
    public-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8989"