tls:
  certificates:
    - certFile: "/home/afzal/Dropbox/secure/ssl/fzryzen/fzryzen.local.crt"
      keyFile: "/home/afzal/Dropbox/secure/ssl/fzryzen/fzryzen.local.key"

  stores:
    default:
      defaultCertificate:
      - certFile: "/home/afzal/Dropbox/secure/ssl/fzryzen/fzryzen.local.crt"
        keyFile: "/home/afzal/Dropbox/secure/ssl/fzryzen/fzryzen.local.key"
