http:
  routers:
    shellinabox:
      rule: "PathPrefix(`/shell`)"
      service: "shellinabox"
      middlewares:
        - "strip-shell-prefix"
        - "common-redirect-to-https"

  middlewares:
    strip-shell-prefix:
      stripPrefix:
        prefixes:
          - "/shell"

  services:
    shellinabox:
      loadBalancer:
        servers:
          - url: "http://localhost:4200"
